---
# Source: sidecarInjectorWebhook/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-sidecar-injector-service-account
  namespace: istio-system
  labels:
    app: sidecarInjectorWebhook
    chart: sidecarInjectorWebhook
    heritage: Tiller
    release: release-name
    istio: sidecar-injector

---
# Source: sidecarInjectorWebhook/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-sidecar-injector-istio-system
  labels:
    app: sidecarInjectorWebhook
    chart: sidecarInjectorWebhook
    heritage: Tiller
    release: release-name
    istio: sidecar-injector
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "patch"]

---
# Source: sidecarInjectorWebhook/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-sidecar-injector-admin-role-binding-istio-system
  labels:
    app: sidecarInjectorWebhook
    chart: sidecarInjectorWebhook
    heritage: Tiller
    release: release-name
    istio: sidecar-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-sidecar-injector-istio-system
subjects:
  - kind: ServiceAccount
    name: istio-sidecar-injector-service-account
    namespace: istio-system

---
# Source: sidecarInjectorWebhook/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: istio-sidecar-injector
  namespace: istio-system
  labels:
    app: sidecarInjectorWebhook
    chart: sidecarInjectorWebhook
    heritage: Tiller
    release: release-name
    istio: sidecar-injector
spec:
  #loadBalancerIP: 192.168.0.55
  ports:
  - port: 443
    #nodePort: 30443
  selector:
    istio: sidecar-injector
  #type: LoadBalancer

---
# Source: sidecarInjectorWebhook/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-sidecar-injector
  namespace: istio-system
  labels:
    app: sidecarInjectorWebhook
    chart: sidecarInjectorWebhook
    heritage: Tiller
    release: release-name
    istio: sidecar-injector
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: sidecarInjectorWebhook
        chart: sidecarInjectorWebhook
        heritage: Tiller
        release: release-name
        istio: sidecar-injector
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-sidecar-injector-service-account
      containers:
        - name: sidecar-injector-webhook
          image: "istio/sidecar_injector:1.1.17"
          imagePullPolicy: IfNotPresent
          args:
            - --caCertFile=/etc/istio/certs/ca.crt
            - --tlsCertFile=/etc/istio/certs/tls.crt
            - --tlsKeyFile=/etc/istio/certs/tls.key
            - --injectConfig=/etc/istio/inject/config
            - --meshConfig=/etc/istio/config/mesh
            - --healthCheckInterval=2s
            - --healthCheckFile=/health
          volumeMounts:
          - name: config-volume
            mountPath: /etc/istio/config
            readOnly: true
          - name: certs
            mountPath: /etc/istio/certs
            readOnly: true
          - name: inject-config
            mountPath: /etc/istio/inject
            readOnly: true
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/sidecar-injector
                - probe
                - --probe-path=/health
                - --interval=4s
            initialDelaySeconds: 4
            periodSeconds: 4
          readinessProbe:
            exec:
              command:
                - /usr/local/bin/sidecar-injector
                - probe
                - --probe-path=/health
                - --interval=4s
            initialDelaySeconds: 4
            periodSeconds: 4
      volumes:
      - name: config-volume
        configMap:
          name: istio
      - name: certs
        secret:
          secretName: istio.istio-sidecar-injector-service-account
      - name: inject-config
        configMap:
          name: istio-sidecar-injector
          items:
          - key: config
            path: config


---
# Source: sidecarInjectorWebhook/templates/mutatingwebhook.yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: istio-sidecar-injector
  namespace: istio-system
  labels:
    app: sidecarInjectorWebhook
    chart: sidecarInjectorWebhook
    heritage: Tiller
    release: release-name
webhooks:
  - name: sidecar-injector.istio.io
    clientConfig:
      #url: https://istio-sidecar-injector.istio-system.svc:443/inject
      service:
        name: istio-sidecar-injector
        namespace: istio-system
        path: "/inject"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvRENDQWVRQ0NRRDFxazRPbjFZaVhqQU5CZ2txaGtpRzl3MEJBUXNGQURCQU1UNHdQQVlEVlFRREREVnAKYzNScGJ5MXphV1JsWTJGeUxXbHVhbVZqZEc5eUxtbHpkR2x2TFhONWMzUmxiUzV6ZG1NdVkyeDFjM1JsY2k1cwpiMk5oYkRBZUZ3MHhPVEV4TURRd056UTNNak5hRncwME56QXpNakl3TnpRM01qTmFNRUF4UGpBOEJnTlZCQU1NCk5XbHpkR2x2TFhOcFpHVmpZWEl0YVc1cVpXTjBiM0l1YVhOMGFXOHRjM2x6ZEdWdExuTjJZeTVqYkhWemRHVnkKTG14dlkyRnNNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXUyMjNmRWVMbkpQTQp1TlA5VDEzU0dmNS8vellaQ3FSWXdnYmNzc0J1aGN5Y3UwcUNwcVlOMUhaOGhsUW90L2g0M1N6anJhQjdqSzVNCjNiRzgxdGc5dUM2WFpHUFBIZVhoNXdNUHNoeERhVU1hRm9RYTNTc0JScjZwdXpoUFN1QUhkN2FsL1d3TVNmZTMKWGFIMDg5Tng1cDRVdTQwdFBSMWVkYlhOWEIvMVQxRHM5eFc5eUM3WHBZWi9Va3BPZExuclJxdDkwOVAzSGhWdgo5S3ovWFV1TmpPd1hyaVhZQjdJZGQxa1RBSW05aGVwMFpHTzVheUJwekp1ektWeXo0VHg3WHcwV25WTHNMNDhwCmZNeUVlTjk0VWVvWW53TnM0bkpQbldiZVZnODA4dzRFcjlEbVNQbVR6NFNkNUdha1pWVmd3cmhoN2Q4Z0VWaEgKWTR2VzVFWktQUUlEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQk5ZQ2NLZEYxWXowbktKYTk2cnUwVQpUUUx2TXJJY0RWNFFqeURYdW5Kd0l5Wm5GenZtYThENm5ON2Fha0tGdjFWNS9WS29qa25TdjROTEJHRFF1cVNCCmdqRDRZakVLM2MwV0VzMllGMXc5R1o2VkF6OXk1K2FFS1RRbzVCZUtEekZobmNveTRUbThCUmFJLzYzaXFTVmwKUHpreStnbEV3NEtQOVJoek1zc0tnNGJBWjI3RnFpMms2Q1pzWUNCY2V2eXNuVVBRMWMvbDdBRVRWK0ViWFF6awoxd0NSOU9BQkk4N1dGaHhuOFNFTStLUkhPeWN3REo4YjJJaCtibEt5a3B1b08yNktCVHcyeWd1VU1aY3dPb2NTCkZpYk93M2d6UGo1RHZ6Ti8zK2MyWmtkNS9ReitoRzlDWTlDbGhnUlh0YlA3YTJ3Z3JDU01HZ0pVMnR5djNwb0UKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        istio-injection: enabled
